version: '3'

services:
  telemetry-api:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "npm ci && npm run build && npm test"
    environment:
      - PORT=8600
      - ENV_ID=test
      - NODE_ENV=test
      # Enable test auth bypass header in tests
      - TEST_AUTH_BYPASS_ENABLED=true
      # Mock the user-cycle service for token validation
      - USER_CYCLE_GRAPHQL_URL=http://localhost:4000/graphql
    ports:
      - 8600:8600
    volumes:
      - .:/app/
      - /app/node_modules
