version: '3'

services:
  telemetry-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8600
      - ENV_ID=dev
      - DB_HOST=host.docker.internal
      - DB_PORT=5300
      - DB_USER=test
      - DB_PASSWORD=test
      - DB_NAME=telemetry-api
    ports:
      - 8600:8600
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
