version: '3.8'

services:
  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb

  flask-app:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
      - INFLUXDB_DATABASE=beehive_data
    depends_on:
      - influxdb

volumes:
  influxdb-data:
