version: '3'

services:
  telemetry-api:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "npm ci && npm run build && node -e \"
        const { spawn } = require('child_process');
        const server = spawn('node', ['/app/app/telemetry-api.js']);
        
        // Log server output
        server.stdout.on('data', (data) => console.log('SERVER:', data.toString()));
        server.stderr.on('data', (data) => console.error('SERVER ERROR:', data.toString()));
        
        // Give the server time to start
        setTimeout(() => {
          console.log('Running tests...');
          const test = spawn('npm', ['test'], { stdio: 'inherit' });
          
          test.on('close', (code) => {
            console.log('Tests completed with code:', code);
            server.kill();
            process.exit(code);
          });
        }, 5000);
      \"
      "
    environment:
      - PORT=8600
      - ENV_ID=test
      - NODE_ENV=test
      # Enable test auth bypass header in tests
      - TEST_AUTH_BYPASS_ENABLED=true
      # Mock the user-cycle service for token validation
      - USER_CYCLE_GRAPHQL_URL=http://localhost:4000/graphql
    ports:
      - 8600:8600
    volumes:
      - .:/app/
      - /app/node_modules
