-- +goose Up

ALTER TABLE beehive_metrics
ADD COLUMN IF NOT EXISTS dedupe_key VARCHAR(128);

-- +goose StatementBegin
DO $$
DECLARE
    is_partitioned BOOLEAN;
    month_start TIMESTAMPTZ := date_trunc('month', NOW());
    from_ts TIMESTAMPTZ;
    to_ts TIMESTAMPTZ;
    part_name TEXT;
BEGIN
    SELECT EXISTS (
        SELECT 1
        FROM pg_partitioned_table pt
        JOIN pg_class c ON c.oid = pt.partrelid
        WHERE c.relname = 'beehive_metrics'
    ) INTO is_partitioned;

    IF NOT is_partitioned THEN
        ALTER TABLE beehive_metrics RENAME TO beehive_metrics_legacy;

        CREATE TABLE beehive_metrics (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY,
            hive_id VARCHAR(50) NOT NULL,
            temperature_celsius REAL,
            humidity_percent REAL,
            weight_kg REAL,
            dedupe_key VARCHAR(128),
            time TIMESTAMPTZ DEFAULT NOW()
        ) PARTITION BY RANGE (time);
    END IF;

    EXECUTE 'CREATE TABLE IF NOT EXISTS beehive_metrics_default PARTITION OF beehive_metrics DEFAULT';

    FOR i IN 0..2 LOOP
        from_ts := month_start + make_interval(months => i);
        to_ts := month_start + make_interval(months => i + 1);
        part_name := format('beehive_metrics_p%s', to_char(from_ts, 'YYYYMM'));

        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS %I PARTITION OF beehive_metrics FOR VALUES FROM (%L) TO (%L)',
            part_name,
            from_ts,
            to_ts
        );
    END LOOP;

    IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_name = 'beehive_metrics_legacy'
    ) THEN
        INSERT INTO beehive_metrics (
            id,
            hive_id,
            temperature_celsius,
            humidity_percent,
            weight_kg,
            dedupe_key,
            time
        )
        SELECT
            id,
            hive_id,
            temperature_celsius,
            humidity_percent,
            weight_kg,
            dedupe_key,
            time
        FROM beehive_metrics_legacy;

        DROP TABLE beehive_metrics_legacy;
    END IF;
END
$$;
-- +goose StatementEnd

CREATE INDEX IF NOT EXISTS idx_beehive_metrics_hive_id ON beehive_metrics (hive_id);
CREATE INDEX IF NOT EXISTS idx_beehive_metrics_time ON beehive_metrics (time);
CREATE INDEX IF NOT EXISTS idx_beehive_metrics_hive_time_desc ON beehive_metrics (hive_id, time DESC);
CREATE INDEX IF NOT EXISTS idx_beehive_metrics_temp_hive_time_desc ON beehive_metrics (hive_id, time DESC) WHERE temperature_celsius IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_beehive_metrics_humidity_hive_time_desc ON beehive_metrics (hive_id, time DESC) WHERE humidity_percent IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_beehive_metrics_weight_hive_time_desc ON beehive_metrics (hive_id, time DESC) WHERE weight_kg IS NOT NULL;

CREATE TABLE IF NOT EXISTS beehive_metric_dedupe (
    hive_id VARCHAR(50) NOT NULL,
    dedupe_key VARCHAR(128) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (hive_id, dedupe_key)
);

INSERT INTO beehive_metric_dedupe (hive_id, dedupe_key)
SELECT DISTINCT hive_id, dedupe_key
FROM beehive_metrics
WHERE dedupe_key IS NOT NULL
ON CONFLICT (hive_id, dedupe_key) DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('beehive_metrics', 'id'),
    GREATEST((SELECT COALESCE(MAX(id), 1) FROM beehive_metrics), 1),
    true
);

-- +goose StatementBegin
DO $$
DECLARE
    is_partitioned BOOLEAN;
    month_start TIMESTAMPTZ := date_trunc('month', NOW());
    from_ts TIMESTAMPTZ;
    to_ts TIMESTAMPTZ;
    part_name TEXT;
BEGIN
    SELECT EXISTS (
        SELECT 1
        FROM pg_partitioned_table pt
        JOIN pg_class c ON c.oid = pt.partrelid
        WHERE c.relname = 'entrance_observer'
    ) INTO is_partitioned;

    IF NOT is_partitioned THEN
        ALTER TABLE entrance_observer RENAME TO entrance_observer_legacy;

        CREATE TABLE entrance_observer (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY,
            hive_id VARCHAR(50) NOT NULL,
            box_id VARCHAR(50) NOT NULL,
            bees_out REAL,
            bees_in REAL,
            time TIMESTAMPTZ DEFAULT NOW(),
            net_flow FLOAT,
            avg_speed_px_per_frame FLOAT,
            p95_speed_px_per_frame FLOAT,
            stationary_bees_count INT,
            detected_bees INT,
            bee_interactions INT
        ) PARTITION BY RANGE (time);
    END IF;

    EXECUTE 'CREATE TABLE IF NOT EXISTS entrance_observer_default PARTITION OF entrance_observer DEFAULT';

    FOR i IN 0..2 LOOP
        from_ts := month_start + make_interval(months => i);
        to_ts := month_start + make_interval(months => i + 1);
        part_name := format('entrance_observer_p%s', to_char(from_ts, 'YYYYMM'));

        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS %I PARTITION OF entrance_observer FOR VALUES FROM (%L) TO (%L)',
            part_name,
            from_ts,
            to_ts
        );
    END LOOP;

    IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_name = 'entrance_observer_legacy'
    ) THEN
        INSERT INTO entrance_observer (
            id,
            hive_id,
            box_id,
            bees_out,
            bees_in,
            time,
            net_flow,
            avg_speed_px_per_frame,
            p95_speed_px_per_frame,
            stationary_bees_count,
            detected_bees,
            bee_interactions
        )
        SELECT
            id,
            hive_id,
            box_id,
            bees_out,
            bees_in,
            time,
            net_flow,
            avg_speed_px_per_frame,
            p95_speed_px_per_frame,
            stationary_bees_count,
            detected_bees,
            bee_interactions
        FROM entrance_observer_legacy;

        DROP TABLE entrance_observer_legacy;
    END IF;
END
$$;
-- +goose StatementEnd

CREATE INDEX IF NOT EXISTS idx_entrance_observer_hive_box ON entrance_observer (hive_id, box_id);
CREATE INDEX IF NOT EXISTS idx_entrance_observer_time ON entrance_observer (time);
CREATE INDEX IF NOT EXISTS idx_entrance_observer_hive_time_desc ON entrance_observer (hive_id, time DESC);
CREATE INDEX IF NOT EXISTS idx_entrance_observer_hive_box_time_desc ON entrance_observer (hive_id, box_id, time DESC);

SELECT setval(
    pg_get_serial_sequence('entrance_observer', 'id'),
    GREATEST((SELECT COALESCE(MAX(id), 1) FROM entrance_observer), 1),
    true
);

-- +goose StatementBegin
CREATE OR REPLACE FUNCTION ingest_beehive_metrics_batch(_metrics JSONB)
RETURNS INTEGER
LANGUAGE plpgsql
AS $$
DECLARE
    inserted_count INTEGER;
BEGIN
    WITH raw_metrics AS (
        SELECT
            m.hive_id,
            m.temperature_celsius,
            m.humidity_percent,
            m.weight_kg,
            m.dedupe_key,
            COALESCE(m.time, NOW()) AS time,
            CASE
                WHEN m.dedupe_key IS NULL THEN NULL
                ELSE ROW_NUMBER() OVER (
                    PARTITION BY m.hive_id, m.dedupe_key
                    ORDER BY COALESCE(m.time, NOW()), m.hive_id
                )
            END AS dedupe_rank
        FROM jsonb_to_recordset(_metrics) AS m(
            hive_id TEXT,
            temperature_celsius DOUBLE PRECISION,
            humidity_percent DOUBLE PRECISION,
            weight_kg DOUBLE PRECISION,
            dedupe_key TEXT,
            time TIMESTAMPTZ
        )
    ),
    inserted_keys AS (
        INSERT INTO beehive_metric_dedupe (hive_id, dedupe_key)
        SELECT hive_id, dedupe_key
        FROM raw_metrics
        WHERE dedupe_key IS NOT NULL AND dedupe_rank = 1
        ON CONFLICT (hive_id, dedupe_key) DO NOTHING
        RETURNING hive_id, dedupe_key
    )
    INSERT INTO beehive_metrics (
        hive_id,
        temperature_celsius,
        humidity_percent,
        weight_kg,
        dedupe_key,
        time
    )
    SELECT
        m.hive_id,
        m.temperature_celsius,
        m.humidity_percent,
        m.weight_kg,
        m.dedupe_key,
        m.time
    FROM raw_metrics m
    LEFT JOIN inserted_keys k
        ON m.hive_id = k.hive_id
        AND m.dedupe_key = k.dedupe_key
    WHERE m.dedupe_key IS NULL
        OR (m.dedupe_rank = 1 AND k.hive_id IS NOT NULL);

    GET DIAGNOSTICS inserted_count = ROW_COUNT;
    RETURN inserted_count;
END;
$$;
-- +goose StatementEnd

-- +goose StatementBegin
CREATE OR REPLACE FUNCTION ingest_entrance_movement_batch(_movements JSONB)
RETURNS INTEGER
LANGUAGE plpgsql
AS $$
DECLARE
    inserted_count INTEGER;
BEGIN
    INSERT INTO entrance_observer (
        hive_id,
        box_id,
        bees_out,
        bees_in,
        net_flow,
        avg_speed_px_per_frame,
        p95_speed_px_per_frame,
        stationary_bees_count,
        detected_bees,
        bee_interactions,
        time
    )
    SELECT
        m.hive_id,
        m.box_id,
        m.bees_out,
        m.bees_in,
        m.net_flow,
        m.avg_speed_px_per_frame,
        m.p95_speed_px_per_frame,
        m.stationary_bees_count,
        m.detected_bees,
        m.bee_interactions,
        COALESCE(m.time, NOW())
    FROM jsonb_to_recordset(_movements) AS m(
        hive_id TEXT,
        box_id TEXT,
        bees_out DOUBLE PRECISION,
        bees_in DOUBLE PRECISION,
        net_flow DOUBLE PRECISION,
        avg_speed_px_per_frame DOUBLE PRECISION,
        p95_speed_px_per_frame DOUBLE PRECISION,
        stationary_bees_count INTEGER,
        detected_bees INTEGER,
        bee_interactions INTEGER,
        time TIMESTAMPTZ
    );

    GET DIAGNOSTICS inserted_count = ROW_COUNT;
    RETURN inserted_count;
END;
$$;
-- +goose StatementEnd

-- +goose Down

DROP FUNCTION IF EXISTS ingest_entrance_movement_batch(JSONB);
DROP FUNCTION IF EXISTS ingest_beehive_metrics_batch(JSONB);
