package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.48

import (
	"context"
	"errors"
	"strconv"
	"time"

	logger "github.com/Gratheon/log-lib-go"
	"github.com/Gratheon/telemetry-api/graph/generated"
	"github.com/Gratheon/telemetry-api/graph/model"
	"github.com/Gratheon/telemetry-api/internal/telemetry"
)

func graphqlTelemetryError(code int, message string) *model.TelemetryError {
	codeValue := strconv.Itoa(code)
	return &model.TelemetryError{
		Message: &message,
		Code:    &codeValue,
	}
}

func wrapKnownError(err error) *model.TelemetryError {
	var telemetryErr *telemetry.ServerError
	if errors.As(err, &telemetryErr) {
		return graphqlTelemetryError(telemetryErr.ErrorCode, telemetryErr.Message)
	}

	logger.Error("unexpected telemetry error", map[string]interface{}{"error": err.Error()})
	return graphqlTelemetryError(telemetry.ErrorCodeInternal, "Internal server error")
}

func validateTimeRange(timeRangeMin *int) *model.TelemetryError {
	if timeRangeMin == nil {
		return nil
	}
	if *timeRangeMin <= 0 {
		return graphqlTelemetryError(telemetry.ErrorCodeInvalidTimeRange, "Time range must be positive")
	}
	if *timeRangeMin > 60*24*7 {
		return graphqlTelemetryError(telemetry.ErrorCodeInvalidTimeRange, "Time range cannot exceed 7 days")
	}
	return nil
}

func validateMaxPoints(maxPoints *int) *model.TelemetryError {
	if maxPoints == nil {
		return nil
	}
	if *maxPoints <= 0 {
		return graphqlTelemetryError(telemetry.ErrorCodeInvalidInput, "maxPoints must be positive")
	}
	if *maxPoints > 10000 {
		return graphqlTelemetryError(telemetry.ErrorCodeInvalidInput, "maxPoints cannot exceed 10000")
	}
	return nil
}

func toMetricList(points []telemetry.MetricPoint) *model.MetricFloatList {
	metrics := make([]*model.MetricFloat, 0, len(points))
	for _, point := range points {
		metrics = append(metrics, &model.MetricFloat{
			T: point.T,
			V: point.V,
		})
	}
	return &model.MetricFloatList{Metrics: metrics}
}

func toEntranceMovementList(records []telemetry.EntranceMovementRecord) *model.EntranceMovementList {
	metrics := make([]*model.EntranceMovementRecord, 0, len(records))
	for _, record := range records {
		metrics = append(metrics, &model.EntranceMovementRecord{
			ID:              strconv.FormatInt(record.ID, 10),
			HiveID:          record.HiveID,
			BoxID:           record.BoxID,
			BeesOut:         record.BeesOut,
			BeesIn:          record.BeesIn,
			Time:            record.Time,
			NetFlow:         record.NetFlow,
			AvgSpeed:        record.AvgSpeed,
			P95Speed:        record.P95Speed,
			StationaryBees:  record.StationaryBees,
			DetectedBees:    record.DetectedBees,
			BeeInteractions: record.BeeInteractions,
		})
	}
	return &model.EntranceMovementList{Metrics: metrics}
}

func toPopulationMetricsList(records []telemetry.PopulationMetricRecord) *model.PopulationMetricsList {
	metrics := make([]*model.PopulationMetric, 0, len(records))
	for _, record := range records {
		metrics = append(metrics, &model.PopulationMetric{
			T:               record.T,
			BeeCount:        record.BeeCount,
			DroneCount:      record.DroneCount,
			VarroaMiteCount: record.VarroaMiteCount,
			InspectionID:    record.InspectionID,
		})
	}
	return &model.PopulationMetricsList{Metrics: metrics}
}

// AddMetric is the resolver for the addMetric field.
func (r *mutationResolver) AddMetric(ctx context.Context, hiveID string, fields model.MetricSetInput) (model.AddMetricResult, error) {
	err := telemetry.AddIoTMetrics(ctx, r.Store, []telemetry.RESTMetricInput{{
		HiveID: telemetry.JSONID(hiveID),
		Fields: telemetry.MetricFields{
			TemperatureCelsius: fields.TemperatureCelsius,
			HumidityPercent:    fields.HumidityPercent,
			WeightKg:           fields.WeightKg,
		},
	}})
	if err != nil {
		return wrapKnownError(err), nil
	}

	message := "OK"
	return &model.AddMetricMessage{Message: &message}, nil
}

// AddPopulationMetric is the resolver for the addPopulationMetric field.
func (r *mutationResolver) AddPopulationMetric(ctx context.Context, hiveID string, fields model.PopulationMetricInput, inspectionID *string, timestamp *time.Time) (model.AddMetricResult, error) {
	payload := telemetry.PopulationMetricFields{
		BeeCount:        fields.BeeCount,
		DroneCount:      fields.DroneCount,
		VarroaMiteCount: fields.VarroaMiteCount,
	}
	if payload.Empty() {
		return graphqlTelemetryError(telemetry.ErrorCodeInvalidInput, "Fields are required"), nil
	}

	if err := r.Store.WritePopulationMetrics(ctx, hiveID, payload, inspectionID, timestamp); err != nil {
		return wrapKnownError(err), nil
	}

	message := "OK"
	return &model.AddMetricMessage{Message: &message}, nil
}

// TemperatureCelsius is the resolver for the temperatureCelsius field.
func (r *queryResolver) TemperatureCelsius(ctx context.Context, hiveID string, timeRangeMin *int, maxPoints *int) (model.MetricListResult, error) {
	if err := validateTimeRange(timeRangeMin); err != nil {
		return err, nil
	}
	if err := validateMaxPoints(maxPoints); err != nil {
		return err, nil
	}

	rangeMin := 60
	if timeRangeMin != nil {
		rangeMin = *timeRangeMin
	}

	points, err := r.Store.ReadMetrics(ctx, hiveID, rangeMin, "temperatureCelsius", maxPoints)
	if err != nil {
		return wrapKnownError(err), nil
	}
	return toMetricList(points), nil
}

// HumidityPercent is the resolver for the humidityPercent field.
func (r *queryResolver) HumidityPercent(ctx context.Context, hiveID string, timeRangeMin *int, maxPoints *int) (model.MetricListResult, error) {
	if err := validateTimeRange(timeRangeMin); err != nil {
		return err, nil
	}
	if err := validateMaxPoints(maxPoints); err != nil {
		return err, nil
	}

	rangeMin := 60
	if timeRangeMin != nil {
		rangeMin = *timeRangeMin
	}

	points, err := r.Store.ReadMetrics(ctx, hiveID, rangeMin, "humidityPercent", maxPoints)
	if err != nil {
		return wrapKnownError(err), nil
	}
	return toMetricList(points), nil
}

// WeightKg is the resolver for the weightKg field.
func (r *queryResolver) WeightKg(ctx context.Context, hiveID string, timeRangeMin *int, maxPoints *int) (model.MetricListResult, error) {
	if err := validateTimeRange(timeRangeMin); err != nil {
		return err, nil
	}
	if err := validateMaxPoints(maxPoints); err != nil {
		return err, nil
	}

	rangeMin := 60
	if timeRangeMin != nil {
		rangeMin = *timeRangeMin
	}

	points, err := r.Store.ReadMetrics(ctx, hiveID, rangeMin, "weightKg", maxPoints)
	if err != nil {
		return wrapKnownError(err), nil
	}
	return toMetricList(points), nil
}

// WeightKgAggregated is the resolver for the weightKgAggregated field.
func (r *queryResolver) WeightKgAggregated(ctx context.Context, hiveID string, days int, aggregation *model.AggregationType) (model.MetricListResult, error) {
	if days <= 0 {
		return graphqlTelemetryError(telemetry.ErrorCodeInvalidTimeRange, "Days must be positive"), nil
	}
	if days > 365 {
		return graphqlTelemetryError(telemetry.ErrorCodeInvalidTimeRange, "Days cannot exceed 365"), nil
	}

	aggregationValue := model.AggregationTypeDailyAvg.String()
	if aggregation != nil {
		aggregationValue = aggregation.String()
	}

	points, err := r.Store.ReadAggregatedWeightMetrics(ctx, hiveID, days, aggregationValue)
	if err != nil {
		return wrapKnownError(err), nil
	}
	return toMetricList(points), nil
}

// EntranceMovementToday is the resolver for the entranceMovementToday field.
func (r *queryResolver) EntranceMovementToday(ctx context.Context, hiveID string, boxID string) (*model.BeeMovementInOutResult, error) {
	result, err := r.Store.ReadAggregatedMetricsFromToday(ctx, hiveID, boxID)
	if err != nil {
		return nil, err
	}

	return &model.BeeMovementInOutResult{
		BeesIn:          result.BeesIn,
		BeesOut:         result.BeesOut,
		NetFlow:         result.NetFlow,
		AvgSpeed:        result.AvgSpeed,
		P95Speed:        result.P95Speed,
		StationaryBees:  result.StationaryBees,
		DetectedBees:    result.DetectedBees,
		BeeInteractions: result.BeeInteractions,
		Time:            result.Time,
	}, nil
}

// EntranceMovement is the resolver for the entranceMovement field.
func (r *queryResolver) EntranceMovement(ctx context.Context, hiveID string, boxID *string, timeFrom time.Time, timeTo time.Time) (model.EntranceMovementResult, error) {
	records, err := r.Store.ReadEntranceMovement(ctx, hiveID, boxID, timeFrom, timeTo)
	if err != nil {
		return wrapKnownError(err), nil
	}
	return toEntranceMovementList(records), nil
}

// PopulationMetrics is the resolver for the populationMetrics field.
func (r *queryResolver) PopulationMetrics(ctx context.Context, hiveID string, days *int) (model.PopulationMetricsResult, error) {
	daysToQuery := 90
	if days != nil {
		daysToQuery = *days
	}

	if daysToQuery <= 0 {
		return graphqlTelemetryError(telemetry.ErrorCodeInvalidTimeRange, "Days must be positive"), nil
	}
	if daysToQuery > 730 {
		return graphqlTelemetryError(telemetry.ErrorCodeInvalidTimeRange, "Days cannot exceed 730"), nil
	}

	records, err := r.Store.ReadPopulationMetrics(ctx, hiveID, daysToQuery)
	if err != nil {
		return wrapKnownError(err), nil
	}
	return toPopulationMetricsList(records), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
