// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
	"time"
)

type AddMetricResult interface {
	IsAddMetricResult()
}

type EntranceMovementResult interface {
	IsEntranceMovementResult()
}

type MetricListResult interface {
	IsMetricListResult()
}

type PopulationMetricsResult interface {
	IsPopulationMetricsResult()
}

type AddMetricMessage struct {
	Message *string `json:"message,omitempty"`
}

func (AddMetricMessage) IsAddMetricResult() {}

type BeeMovementInOutResult struct {
	BeesIn          *float64   `json:"beesIn,omitempty"`
	BeesOut         *float64   `json:"beesOut,omitempty"`
	NetFlow         *float64   `json:"netFlow,omitempty"`
	AvgSpeed        *float64   `json:"avgSpeed,omitempty"`
	P95Speed        *float64   `json:"p95Speed,omitempty"`
	StationaryBees  *int       `json:"stationaryBees,omitempty"`
	DetectedBees    *int       `json:"detectedBees,omitempty"`
	BeeInteractions *int       `json:"beeInteractions,omitempty"`
	Time            *time.Time `json:"time,omitempty"`
}

type EntranceMovementList struct {
	Metrics []*EntranceMovementRecord `json:"metrics,omitempty"`
}

func (EntranceMovementList) IsEntranceMovementResult() {}

type EntranceMovementRecord struct {
	ID              string    `json:"id"`
	HiveID          string    `json:"hiveId"`
	BoxID           string    `json:"boxId"`
	BeesOut         *float64  `json:"beesOut,omitempty"`
	BeesIn          *float64  `json:"beesIn,omitempty"`
	Time            time.Time `json:"time"`
	NetFlow         *float64  `json:"netFlow,omitempty"`
	AvgSpeed        *float64  `json:"avgSpeed,omitempty"`
	P95Speed        *float64  `json:"p95Speed,omitempty"`
	StationaryBees  *int      `json:"stationaryBees,omitempty"`
	DetectedBees    *int      `json:"detectedBees,omitempty"`
	BeeInteractions *int      `json:"beeInteractions,omitempty"`
}

type MetricFloat struct {
	// Timestamp of the metric. We use short-hand name to save bandwidth as it is a repeated metric
	T time.Time `json:"t"`
	// Float value of the metric. We use short-hand name to save bandwidth as it is a repeated metric
	V *float64 `json:"v,omitempty"`
}

type MetricFloatList struct {
	Metrics []*MetricFloat `json:"metrics,omitempty"`
}

func (MetricFloatList) IsMetricListResult() {}

type MetricSetInput struct {
	TemperatureCelsius *float64 `json:"temperatureCelsius,omitempty"`
	HumidityPercent    *float64 `json:"humidityPercent,omitempty"`
	WeightKg           *float64 `json:"weightKg,omitempty"`
}

type Mutation struct {
}

type PopulationMetric struct {
	// Timestamp of the metric
	T time.Time `json:"t"`
	// Bee count
	BeeCount *int `json:"beeCount,omitempty"`
	// Drone count
	DroneCount *int `json:"droneCount,omitempty"`
	// Varroa mite count
	VarroaMiteCount *int `json:"varroaMiteCount,omitempty"`
	// Inspection ID if available
	InspectionID *string `json:"inspectionId,omitempty"`
}

type PopulationMetricInput struct {
	BeeCount        *int `json:"beeCount,omitempty"`
	DroneCount      *int `json:"droneCount,omitempty"`
	VarroaMiteCount *int `json:"varroaMiteCount,omitempty"`
}

type PopulationMetricsList struct {
	Metrics []*PopulationMetric `json:"metrics,omitempty"`
}

func (PopulationMetricsList) IsPopulationMetricsResult() {}

type Query struct {
}

type TelemetryError struct {
	Message *string `json:"message,omitempty"`
	Code    *string `json:"code,omitempty"`
}

func (TelemetryError) IsEntranceMovementResult() {}

func (TelemetryError) IsMetricListResult() {}

func (TelemetryError) IsPopulationMetricsResult() {}

func (TelemetryError) IsAddMetricResult() {}

type AggregationType string

const (
	AggregationTypeDailyAvg AggregationType = "DAILY_AVG"
	AggregationTypeDailyMax AggregationType = "DAILY_MAX"
	AggregationTypeDailyMin AggregationType = "DAILY_MIN"
)

var AllAggregationType = []AggregationType{
	AggregationTypeDailyAvg,
	AggregationTypeDailyMax,
	AggregationTypeDailyMin,
}

func (e AggregationType) IsValid() bool {
	switch e {
	case AggregationTypeDailyAvg, AggregationTypeDailyMax, AggregationTypeDailyMin:
		return true
	}
	return false
}

func (e AggregationType) String() string {
	return string(e)
}

func (e *AggregationType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AggregationType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AggregationType", str)
	}
	return nil
}

func (e AggregationType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
